Deserialize
40ants/cl-prevalence pull request #17
Opened 2020-11-06 10:57 UTC by Ambrevar

Fixes #16. 

As discussed, this fixes struct deserialization when they have a non-default constructor on SBCL, CCL, CLisp and ECL.
For other compilers, it raises an error.

Better: I've introduced 2 generic functions which allow for customizing the deserialization of structs and classes according to their symbol.

So if I want to specialize the deserialization of `quri.uri:uri`, I can specialize this way:

```lisp
(defmethod deserialize-struct ((struct-symbol (eql 'quri.uri:uri)) slots deserialized-objects)
  ...)
```

Thoughts?

2020-11-06 13:13 UTC, svetlyak40wt requested changes

2020-11-06 13:13 UTC, svetlyak40wt commented on src/serialization/sexp.lisp
> +                     (error "Does not know how to deserialize non-default constructor"))))
Lets improve this error message like this:

```lisp
(error "Do not know how to deserialize struct ~S with non-default constructor"
           struct-symbol)
```

2020-11-06 13:31 UTC, Ambrevar commented
Done.

2020-11-09 15:57 UTC, Ambrevar commented
Don't merge!

Found a bug in Nyxt which breaks object reference when deserializing.

I'll investigate.

2020-11-09 16:06 UTC, Ambrevar commented
Fixed in 
df1da344ddf1b188c3ffc5c54808d94266356f79.

2020-11-09 16:11 UTC, svetlyak40wt approved these changes

2020-11-09 16:12 UTC, svetlyak40wt commented
Ok, thank you!

Let's merge it now!

2020-11-09 16:12 UTC, merged

2020-11-09 18:10 UTC, Ambrevar commented
Thanks!